package com.bjyw.bjckyh.bean.daobean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bjyw.bjckyh.bean.daobean.Inspect;
import com.bjyw.bjckyh.bean.daobean.InspectConsumable;
import com.bjyw.bjckyh.bean.daobean.InspectEnvironMent;
import com.bjyw.bjckyh.bean.daobean.InspectEquipMent;

import com.bjyw.bjckyh.bean.daobean.InspectDao;
import com.bjyw.bjckyh.bean.daobean.InspectConsumableDao;
import com.bjyw.bjckyh.bean.daobean.InspectEnvironMentDao;
import com.bjyw.bjckyh.bean.daobean.InspectEquipMentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig inspectDaoConfig;
    private final DaoConfig inspectConsumableDaoConfig;
    private final DaoConfig inspectEnvironMentDaoConfig;
    private final DaoConfig inspectEquipMentDaoConfig;

    private final InspectDao inspectDao;
    private final InspectConsumableDao inspectConsumableDao;
    private final InspectEnvironMentDao inspectEnvironMentDao;
    private final InspectEquipMentDao inspectEquipMentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        inspectDaoConfig = daoConfigMap.get(InspectDao.class).clone();
        inspectDaoConfig.initIdentityScope(type);

        inspectConsumableDaoConfig = daoConfigMap.get(InspectConsumableDao.class).clone();
        inspectConsumableDaoConfig.initIdentityScope(type);

        inspectEnvironMentDaoConfig = daoConfigMap.get(InspectEnvironMentDao.class).clone();
        inspectEnvironMentDaoConfig.initIdentityScope(type);

        inspectEquipMentDaoConfig = daoConfigMap.get(InspectEquipMentDao.class).clone();
        inspectEquipMentDaoConfig.initIdentityScope(type);

        inspectDao = new InspectDao(inspectDaoConfig, this);
        inspectConsumableDao = new InspectConsumableDao(inspectConsumableDaoConfig, this);
        inspectEnvironMentDao = new InspectEnvironMentDao(inspectEnvironMentDaoConfig, this);
        inspectEquipMentDao = new InspectEquipMentDao(inspectEquipMentDaoConfig, this);

        registerDao(Inspect.class, inspectDao);
        registerDao(InspectConsumable.class, inspectConsumableDao);
        registerDao(InspectEnvironMent.class, inspectEnvironMentDao);
        registerDao(InspectEquipMent.class, inspectEquipMentDao);
    }
    
    public void clear() {
        inspectDaoConfig.clearIdentityScope();
        inspectConsumableDaoConfig.clearIdentityScope();
        inspectEnvironMentDaoConfig.clearIdentityScope();
        inspectEquipMentDaoConfig.clearIdentityScope();
    }

    public InspectDao getInspectDao() {
        return inspectDao;
    }

    public InspectConsumableDao getInspectConsumableDao() {
        return inspectConsumableDao;
    }

    public InspectEnvironMentDao getInspectEnvironMentDao() {
        return inspectEnvironMentDao;
    }

    public InspectEquipMentDao getInspectEquipMentDao() {
        return inspectEquipMentDao;
    }

}
