package com.bjyw.bjckyh.bean.daobean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bjyw.bjckyh.bean.daobean.Inspect;
import com.bjyw.bjckyh.bean.daobean.InspectEnvironMent;

import com.bjyw.bjckyh.bean.daobean.InspectDao;
import com.bjyw.bjckyh.bean.daobean.InspectEnvironMentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig inspectDaoConfig;
    private final DaoConfig inspectEnvironMentDaoConfig;

    private final InspectDao inspectDao;
    private final InspectEnvironMentDao inspectEnvironMentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        inspectDaoConfig = daoConfigMap.get(InspectDao.class).clone();
        inspectDaoConfig.initIdentityScope(type);

        inspectEnvironMentDaoConfig = daoConfigMap.get(InspectEnvironMentDao.class).clone();
        inspectEnvironMentDaoConfig.initIdentityScope(type);

        inspectDao = new InspectDao(inspectDaoConfig, this);
        inspectEnvironMentDao = new InspectEnvironMentDao(inspectEnvironMentDaoConfig, this);

        registerDao(Inspect.class, inspectDao);
        registerDao(InspectEnvironMent.class, inspectEnvironMentDao);
    }
    
    public void clear() {
        inspectDaoConfig.clearIdentityScope();
        inspectEnvironMentDaoConfig.clearIdentityScope();
    }

    public InspectDao getInspectDao() {
        return inspectDao;
    }

    public InspectEnvironMentDao getInspectEnvironMentDao() {
        return inspectEnvironMentDao;
    }

}
